stages:
  - test
  - build
  - deploy

variables:
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  STATIC_ROOT: "/app/staticfiles"

test:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - python manage.py test
    - python manage.py check --deploy

build:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:
    - docker build -t $DOCKER_TAG .
    - docker push $DOCKER_TAG

deploy:
  stage: deploy
  image: alpine:3.16
  script:
    - apk add --no-cache openssh-client
    - ssh -o StrictHostKeyChecking=no user@server_ip "
      cd /path/to/SLink &&
      docker-compose pull &&
      docker-compose up -d
      "
