stages:
  - test
  - build
  - deploy

variables:
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

test:
  stage: test
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
  script:
    - python src/manage.py test

build:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_TAG .
    - docker push $DOCKER_TAG

deploy:
  stage: deploy
  image: ubuntu:20.04
  before_script:
    - apt-get update && apt-get install -y ssh-client rsync
  script:
    - ssh -o StrictHostKeyChecking=no user@your-server-ip "docker pull $DOCKER_TAG"
    - ssh user@your-server-ip "docker-compose down && docker-compose up -d"
  only:
    - main  # فقط برای branch اصلی اجرا شود